### ISSUE TITLE
[BUG] Path parsing error

### ISSUE THREAD

**Issue by NoraH1to** [SharpGoldWaveMaker/sutras#7]
## Environment

 - Windows 10
 - node 18.20.3
 - vite 5.3.1
 - vitepress 1.2.3

## What happened

```md
## Demo

<demo path="./demo/basic-usage.vue" />
```

Then I got the error:

```
Fail to resolve import "./demo\basic-usage.vue" from "xxx/yyy/index.md"
```

**Comment by NoraH1to** [comment]
Fix here I guess https://github.com/SharpGoldWaveMaker/sutras/blob/396b17d1bed463551f1d1d5dd093779d6a63a98c/plugin/src/vite/parse/demo.ts#L62

**Comment by SharpGoldWaveMaker** [comment]
> Wrap with the `normalize` function I guess
> 
> https://github.com/SharpGoldWaveMaker/sutras/blob/396b17d1bed463551f1d1d5dd093779d6a63a98c/plugin/src/vite/parse/demo.ts#L62

Thanks for your feedback, I will conduct a complete test of the win environment

**Comment by SharpGoldWaveMaker** [comment]
> Wrap with the `normalize` function I guess
> 
> https://github.com/SharpGoldWaveMaker/sutras/blob/396b17d1bed463551f1d1d5dd093779d6a63a98c/plugin/src/vite/parse/demo.ts#L62

I have resolved the issue. Please:

**1.Delete the pnpm-lock.json file**
**2.Upgrade the relevant packages:**
pnpm upgrade @sgwm-sutras/plugin@latest @sgwm-sutras/ui@latest
